# URL de la base de datos (reemplaza 'nombre_tu_db' por el nombre real)
spring.datasource.url=jdbc:postgresql://localhost:5432/nombre_tu_db

# Credenciales de acceso
spring.datasource.username=postgres
spring.datasource.password=tu_contraseña