spring.application.name=microservicio_kpi
# Conexión a Base de Datos Local
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8087
# JPA / Hibernate
# 'update' creará las tablas automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Comentario equipo: Usamos variables de entorno para no dejar
# las contraseñas expuestas en el código fuente.

# Configuración del Circuit Breaker
resilience4j.circuitbreaker.instances.kpiService.sliding-window-size=5
resilience4j.circuitbreaker.instances.kpiService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.kpiService.wait-duration-in-open-state=10000
