# URL de la base de datos (reemplaza 'nombre_tu_db' por el nombre real)
spring.datasource.url=${DB_HOST}

# Credenciales de acceso
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}