spring.application.name=microservicio_kpi

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8087

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


resilience4j.circuitbreaker.instances.kpiService.sliding-window-size=5
resilience4j.circuitbreaker.instances.kpiService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.kpiService.wait-duration-in-open-state=10000
